### ISSUE TITLE
TypeError: OAuth2Strategy requires a clientID option

### ISSUE THREAD

**Issue by jamesonessit** [forseti-security/forseti-visualizer#38]
ClientID required to test build

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/Users/ja/Documents/Github/forseti-visualizer/forseti-api/node_modules/passport-oauth2/lib/strategy.js:86:34)
    at new Strategy (/Users/ja/Documents/Github/forseti-visualizer/forseti-api/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
    at Object.<anonymous> (/Users/ja/Documents/Github/forseti-visualizer/forseti-api/server/services/oauth2.js:59:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at loader (/Users/ja/Documents/Github/forseti-visualizer/forseti-api/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ja/Documents/Github/forseti-visualizer/forseti-api/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by garrettwong** [comment]
This will be resolved in an upcoming fairly large PR.

In the meantime, you can reference the README on the forseti-api page for getting around this:
https://github.com/forseti-security/forseti-visualizer/blob/master/forseti-api/README.md

**Comment by garrettwong** [comment]
This will be deprecated.  There is a work in progress branch here that you could test:
https://github.com/forseti-security/forseti-visualizer/tree/cleanup-and-streamline

**Comment by garrettwong** [comment]
The use of config.json has been deprecated as of #49.
