### ISSUE TITLE
Cannot find module './server/config.json' ???

### ISSUE THREAD

**Issue by jf-marquis-Adeo** [forseti-security/forseti-visualizer#39]
I have an error while testing in standalone or deploying via Cloudrun.
Does anyone know where it come from ?
Error: Cannot find module './server/config.json' at Function.Module._resolveFilename (module.js:548:15) at Function.Module._load (module.js:475:25) at Module.require (module.js:597:17) at require (internal/module.js:11:18) at Object.<anonymous> (/usr/src/app/server.js:21:1) at Module._compile (module.js:653:30) at loader (/usr/src/app/node_modules/babel-register/lib/node.js:144:5) at Object.require.extensions.(anonymous function) [as .js] (/usr/src/app/node_modules/babel-register/lib/node.js:154:7) at Module.load (module.js:566:32) at tryModuleLoad (module.js:506:12)
thanks for your help

**Comment by jf-marquis-Adeo** [comment]
just don't find the right doc 
sorry
